/**
 * Builds a real, legible PDF proof-of-delivery for the seed — a signed delivery
 * receipt, not a placeholder blob. PDF is a text-based format and Helvetica is one of
 * the 14 fonts every viewer ships, so this needs no image library and no binary asset
 * checked into the repo: the bytes are generated, and they open in any PDF viewer.
 */

type PodSpec = {
  reference: string;
  shipper: string;
  carrier: string;
  broker: string;
  origin: string;
  destination: string;
  commodity: string;
  weightLbs: number;
  deliveredAt: Date;
  signedBy: string;
};

/** Escape the three characters that are special inside a PDF string literal. */
function esc(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function contentStream(spec: PodSpec): string {
  const date = spec.deliveredAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const time = spec.deliveredAt.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });

  const rows: Array<[string, string]> = [
    ["Load reference", spec.reference],
    ["Shipper", spec.shipper],
    ["Broker", spec.broker],
    ["Carrier", spec.carrier],
    ["Origin", spec.origin],
    ["Destination", spec.destination],
    ["Commodity", spec.commodity],
    ["Weight", `${spec.weightLbs.toLocaleString("en-US")} lb`],
    ["Delivered", `${date} at ${time}`],
  ];

  const ops: string[] = [];

  // Header band.
  ops.push("0.13 0.14 0.16 rg", "0 712 612 80 re", "f");
  ops.push(
    "BT",
    "1 1 1 rg",
    "/F1 22 Tf",
    "54 748 Td",
    `(${esc("PROOF OF DELIVERY")} ) Tj`,
    "/F2 10 Tf",
    "0 -18 Td",
    `(${esc(`LoadFlow  ·  ${spec.broker}`)}) Tj`,
    "ET",
  );

  // Field table.
  let y = 660;
  for (const [label, value] of rows) {
    ops.push(
      "BT",
      "0.45 0.45 0.47 rg",
      "/F2 9 Tf",
      `54 ${y} Td`,
      `(${esc(label.toUpperCase())}) Tj`,
      "ET",
    );
    ops.push(
      "BT",
      "0.1 0.1 0.12 rg",
      "/F1 12 Tf",
      `54 ${y - 16} Td`,
      `(${esc(value)}) Tj`,
      "ET",
    );
    // Hairline rule under each field.
    ops.push("0.88 0.88 0.9 RG", "0.5 w", `54 ${y - 24} m 558 ${y - 24} l S`);
    y -= 44;
  }

  // Received-in-good-condition statement.
  ops.push(
    "BT",
    "0.3 0.3 0.32 rg",
    "/F2 9.5 Tf",
    `54 ${y - 6} Td`,
    `(${esc("Received in good order and condition, except as noted. Freight charges are the")}) Tj`,
    "0 -12 Td",
    `(${esc("responsibility of the broker named above.")}) Tj`,
    "ET",
  );

  // Signature block.
  const sigY = y - 70;
  ops.push("0.1 0.1 0.12 RG", "1 w", `54 ${sigY} m 300 ${sigY} l S`);
  ops.push(
    "BT",
    "0.45 0.45 0.47 rg",
    "/F2 8.5 Tf",
    `54 ${sigY - 12} Td`,
    `(${esc(`RECEIVED BY — ${spec.signedBy}`)}) Tj`,
    "ET",
  );

  // A handwritten-looking signature over the rule.
  ops.push("0.11 0.16 0.42 RG", "1.6 w");
  ops.push(
    `62 ${sigY + 6} m`,
    `78 ${sigY + 26} 96 ${sigY - 8} 112 ${sigY + 14} c`,
    `126 ${sigY + 30} 138 ${sigY - 4} 152 ${sigY + 10} c`,
    `168 ${sigY + 24} 182 ${sigY + 2} 205 ${sigY + 18} c`,
    "S",
  );
  ops.push(`150 ${sigY + 2} m`, `168 ${sigY + 22} l`, "S");

  // Date line.
  ops.push("0.1 0.1 0.12 RG", "1 w", `340 ${sigY} m 558 ${sigY} l S`);
  ops.push(
    "BT",
    "0.45 0.45 0.47 rg",
    "/F2 8.5 Tf",
    `340 ${sigY - 12} Td`,
    `(${esc("DATE")}) Tj`,
    "ET",
  );
  ops.push(
    "BT",
    "0.1 0.1 0.12 rg",
    "/F1 12 Tf",
    `340 ${sigY + 6} Td`,
    `(${esc(date)}) Tj`,
    "ET",
  );

  // Footer.
  ops.push(
    "BT",
    "0.55 0.55 0.57 rg",
    "/F2 8 Tf",
    "54 60 Td",
    `(${esc(`Generated by LoadFlow · document is retained against load ${spec.reference}`)}) Tj`,
    "ET",
  );

  return ops.join("\n");
}

export function buildPodPdf(spec: PodSpec): Uint8Array<ArrayBuffer> {
  const content = contentStream(spec);

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] " +
      "/Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(content, "latin1")} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];

  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  // Prisma's Bytes column types as Uint8Array<ArrayBuffer>. A Node Buffer — and
  // anything constructed from one — is Uint8Array<ArrayBufferLike>, which will not
  // assign to it. Allocate a real ArrayBuffer and copy into it.
  const bytes = Buffer.from(pdf, "latin1");
  const out = new Uint8Array<ArrayBuffer>(new ArrayBuffer(bytes.byteLength));
  out.set(bytes);
  return out;
}
